### ISSUE TITLE
Telefonnummer, Email einfügen

### ISSUE THREAD

**Issue by ulphie** [fb71/ulrike-philipp#3]
Bitte, wenn möglich
- meine Telefonnummern in meiner Schreibweise ( 0179-731 31 56, 0341-228 75 37) 
- E-Mail
  wieder oben in die Leiste einfügen
- gern rechtsbündig nach Start - Termine - Impressum folgend

Vielen vielen Dank!!!!

**Comment by fb71** [comment]
Ein Ticket! Das hat schonmal gut funktioniert. Wunderbar :)

Es wäre schön, wenn du dem Ticket einen "sprechenden" Namen geben könntest. So dass man in der Liste schon sehen kann was für eine Aufgabe das ist.

Und im Text kannst du dieselben Formatierungen verwenden wie bei deiner Website. Damit man Anstriche richtig erkennt, sind zum Beispiel 2 Freizeichen am Anfang der Zeile gut.
