### ISSUE TITLE
Neue Website mit Areca

### ISSUE THREAD

**Issue by fb71** [fb71/ulrike-philipp#6]
## Technik der Website Umbauen auf Areca

  - selbe Bedienung und Aussehen
  - aktuelle Probleme bei Darstellung beheben
  - einfache(re) Wartung
  
## Was muss gemacht werden?

  - [x] Markdown
  - [x] interne Links + spezifische URL (mit #, oder als Pfad ohne Endung)
  - [x] externe Links mit target=_blank (?)
  - [x] Browser Back (Pages werden einfach immer übereinander gestapelt)
  - [ ] generelles Page Layout (PageContainer)
  - [ ] Header in HTML (etwas dunkler)
  - ...

**Comment by ulphie** [comment]
Vielen Dank!

---
Von meinem Telefon gesendet
Ulrike Philipp
Coach für The Work of Byron Katie (vtw) und
Dipl. Soz.päd./arb. (FH)
Krisenbegleitung. Strukturberatung.
"Gedanken und Orte aufräumen"
+49179 7313156
***@***.***
http://www.ulrike-philipp.de
http://www.dieaufraeumerinnen.de

19.07.2023 12:07:48 Falko Bräutigam ***@***.***>:

**Comment by fb71** [comment]
Das ist ja cool! Du bekommst EMails, wenn ich dein Projekt ändere... und du liest das sogar. Na, es ist immer gut, wenn man informiert ist, wenn die Programmierer da wieder mal was rumfuddeln. Sheepy und Wizard freuen sich sehr über interessierte "Kunden". :)

**Comment by ulphie** [comment]
Viele Grüße zu euch allen und vielen Dank für euer Tun!
Ich überlege gerade, eine kleine Zwischenmahlzeit einzunehmen. Muss erst 16 Uhr Villaieren. Vielleicht NaBaStuSuppe o Krautpfanne bei Malte...

---
Von meinem Telefon gesendet
Ulrike Philipp
Coach für The Work of Byron Katie (vtw) und
Dipl. Soz.päd./arb. (FH)
Krisenbegleitung. Strukturberatung.
"Gedanken und Orte aufräumen"
+49179 7313156
***@***.***
http://www.ulrike-philipp.de
http://www.dieaufraeumerinnen.de

19.07.2023 12:14:42 Falko Bräutigam ***@***.***>:
